FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      clang-18 \
      cmake \
      git \
      llvm-18-dev \
      python3 \
      ninja-build \
      time && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
